### ISSUE TITLE
Regular expression error of penn_tokenize

### ISSUE THREAD

**Issue by speedcell4** [hplt-project/sacremoses#151]
```python3
from sacremoses import MosesTokenizer

print(MosesTokenizer(lang='en').penn_tokenize("-LRB- This is very nice -RRB-"))
```

got error, and I found changing `lang='en'` to `lang='zh'` doesn't solve the problem.

```
Traceback (most recent call last):
  File ".../scratches/ada.py", line 3, in <module>
    print(MosesTokenizer(lang='en').penn_tokenize("-LRB- This is very nice -RRB-"))
  File ".../python3.9/site-packages/sacremoses/tokenize.py", line 423, in penn_tokenize
    text = regexp.sub(substitution, text)
AttributeError: 'str' object has no attribute 'sub'
```
I think the problem is here, since it is a `str`, not a compiled pattern

https://github.com/hplt-project/sacremoses/blob/65543c34baf589f30260488d882d0060abaa4087/sacremoses/tokenize.py#L93-L96

**Comment by jelmervdl** [comment]
Looks like there's two bugs here:
1) that expression not being compiled, and 
2) changing lang doesn't update the penn expressions as you'd expect
